
consul:
  image: datamgtcloud/consul:latest
  hostname: consul
  dns: 127.0.0.1
  restart: always
  ports:
  - "8500:8500"
  volumes:
  - /data/consul:/data
  environment:
  - CONSUL_OPTIONS=-bootstrap

nginx:
  image: datamgtcloud/consulnginx:latest
  hostname: nginx
  dns: 127.0.0.1
  restart: always
  ports:
  - "80:80"
  links:
  - consul:consul

javademo1:
  image: datamgtcloud/javademo:latest
  hostname: javademo1
  dns: 127.0.0.1
  restart: always
  links:
  - consul:consul

javademo2:
  image: datamgtcloud/javademo:latest
  hostname: javademo2
  dns: 127.0.0.1
  restart: always
  links:
  - consul:consul
